### ISSUE TITLE
Prefill the suggestion on tab press

### ISSUE THREAD

**Issue by jayhawk24** [jayhawk24/shorty#1]
![image](https://user-images.githubusercontent.com/38766415/194771918-d2e0b23e-01f6-45e4-ad19-66b6856b1b43.png)

**Comment by jsvigneshkanna** [comment]
@jayhawk24 

Can you elaborate the issue

**Comment by jayhawk24** [comment]
Once the user is focused on the input box and presses tab button the input box should be filled with the suggestion which you can see as a placeholder
